### PR TITLE
Add Pixel 2 device

### PR DESCRIPTION
**Pull request by jraska**
Virtual devices were problematic with push, but also way slower to execute. Even slower fo processing the outputs.

### CODE REVIEW

**Comment by lordcodes** [comment]
@jraska How are you finding this?
I am using Device Testing via Bitrise so I don't use Firebase Test Lab directly. I have recently had issues that the tests end with a failure saying it crashed, but all the tests pass.
Bitrise support suggest I try a different device. I was using Pixel 2 API 28 before.

**Comment by jraska** [comment]
@lordcodes So far it works good the execution is surprisingly even faster than on Pixel 4 API 29. (Median of 14s compared to 17s) :) 

I had similar failure experience with Pixel 4 In my case it was some crash within Play Store installed on the device. It took some weeks of information ping pong with Firebase Support to get it sorted :D

Different device usually solves this, but they don't have API 30 yet and there is very few on API 29.

**Comment by lordcodes** [comment]
I re-read above, I'm forced to use virtual devices as that must be the deal Bitrise have with Firebase.
You get it included with your Bitrise subscription so worth sticking with until I really need more.

**Comment by jraska** [comment]
This PR was released with [0.22.1](https://github.com/jraska/github-client/releases/tag/0.22.1)

**Pull request merged**
