### PR TITLE
Add launch time reporting

### PR DESCRIPTION
**Pull request by jraska**
- First version to get some production data.
- Most ifno got from here: https://dev.to/pyricau/android-vitals-why-did-my-process-start-4d0e

### CODE REVIEW

**Comment by lordcodes** [comment]
This might interest you:

https://github.com/square/tart

It was created based on all the learnings from the series of blog posts, one of which you linked to, I believe. It doesn't have a stable API yet, but linking to it incase it is useful/interesting. I have been monitoring it.

**Comment by jraska** [comment]
Hey, thanks for sharing :)

I was actually checking that whilst reading the whole series :) My motivation to implement by myself was at the end
- Not depending on highly unstable dependency
- Only a subset of provided functionality required for now
- Get some first hand learning and understanding on how the system behaves by myself

> I have been monitoring it.

You've been monitoring the dependency or did you try to measure the launch time?

What my ideal case would be expose the Play Vitals metrics via API or Google releasing a library how to measure these to provide a standard. Similarly like for [Web Vitals](https://web.dev/vitals/)

**Comment by lordcodes** [comment]
As in I think same as you, I have read the library and was planning to use bits of it myself.

I was informing you of it incase you didn't know. As it turns out you are :D.

**Comment by jraska** [comment]
Thanks anyway :) it is good to know more people are looking into this.

**Pull request merged**
